steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/axial-module-393809/food-site-repo/food-site:v1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/axial-module-393809/food-site-repo/food-site:v1']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'cluster-1'  
      - '--region=us-central1'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/'  

images: ['gcr.io/cloud-builders/docker', 'gcr.io/google.com/cloudsdktool/cloud-sdk']
