steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/axial-module-393809/food-site-repo/food-site:v1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/axial-module-393809/food-site-repo/food-site:v1']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'  # Use the 'run' command to deploy to Cloud Run
      - 'deploy'  # Deploy a new revision
      - 'food-site-service'  # Replace with your Cloud Run service name
      - '--image=us-central1-docker.pkg.dev/axial-module-393809/food-site-repo/food-site:v1'  # Image URL
      - '--platform=managed'
      - '--region=us-central1'  # Replace with your desired region
      - '--port=5000'  # Set the port to 5000
options:
  logging: 'gs://cloud-build-1'  # Specify the Cloud Storage bucket for logs as a string, not an array
