# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-site-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food-site
  template:
    metadata:
      labels:
        app: food-site
    spec:
      containers:
      - name: food-site-container
        image: us-central1-docker.pkg.dev/axial-module-393809/food-site-repo/food-site:v1
        ports:
        - containerPort: 5000
