# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: food-site-service
spec:
  selector:
    app: food-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer  
